#!/usr/bin/env python3
from pathlib import Path

p = Path('.github/apply_lsh_redirections.py')
s = p.read_text()

# The first staged version anchored an insertion on a Python string containing
# an L literal `\n`; make the insertion independent of that escaping detail.
start = s.index("    s = once(s,\n'''    var pipe_partial")
end = s.index("    return s\n\n\ndef executor_file", start)
replacement = '''    insert = r\'''    var redirect_partial = expect_incomplete("printf x >", IncompleteKind.redirection);\n    require(len(redirect_partial.pipeline.commands) == 1);\n    require_bytes(redirect_partial.pipeline.commands[0].words[0].value, "printf");\n\n    var quoted_operator = expect_ready("printf 'a>b' \\\"c<d\\\"");\n    require(len(quoted_operator.commands[0].redirections) == 0);\n    require_bytes(quoted_operator.commands[0].words[1].value, "a>b");\n    require_bytes(quoted_operator.commands[0].words[2].value, "c<d");\n\n\'''\n    s = once(s, '    expect_error("| cat");\\n', insert + '    expect_error("| cat");\\n', 'redirection parser tests')\n'''
s = s[:start] + replacement + s[end:]

# L locals are initialized at declaration. Keep the prepared IO value scoped to
# the successful match arm rather than inventing a sentinel/default value.
old = '''    var prepared: PreparedPipeline;\n    match (prepare_stages(pipeline, input, output, pipes)) {\n        PrepareResult.failed(problem) {\n            close_pipes(pipes);\n            close_stdio(input, output, error);\n            return LaunchResult.redirection_failed(problem);\n        }\n        PrepareResult.ok(value) { prepared = value; }\n    }\n\n    var children: []process.Child = [];\n    var group: ?process.Group = none;\n\n    for (var i: u64 = 0; i < len(pipeline.commands); i += 1) {\n        var command = pipeline.commands[i];\n        var stage = prepared.stages[i];\n        match (spawn_command(command, stage.input, stage.output, error, group, terminal)) {\n            SpawnAttempt.ok(child) {\n                push(children, child);\n                if (i == 0) { group = some(process.group(child)); }\n            }\n            SpawnAttempt.not_found {\n                rollback(children, group, prepared.opened, pipes, input, output, error);\n                return LaunchResult.invalid("command could not be resolved");\n            }\n            SpawnAttempt.failed(number) {\n                rollback(children, group, prepared.opened, pipes, input, output, error);\n                return LaunchResult.launch_failed(failure(command, number));\n            }\n        }\n    }\n\n    close_fds(prepared.opened);\n    close_pipes(pipes);\n    close_stdio(input, output, error);\n    return LaunchResult.ok(LiveJob { children: children, group: group });\n'''
new = '''    match (prepare_stages(pipeline, input, output, pipes)) {\n        PrepareResult.failed(problem) {\n            close_pipes(pipes);\n            close_stdio(input, output, error);\n            return LaunchResult.redirection_failed(problem);\n        }\n        PrepareResult.ok(prepared) {\n            var children: []process.Child = [];\n            var group: ?process.Group = none;\n\n            for (var i: u64 = 0; i < len(pipeline.commands); i += 1) {\n                var command = pipeline.commands[i];\n                var stage = prepared.stages[i];\n                match (spawn_command(command, stage.input, stage.output, error, group, terminal)) {\n                    SpawnAttempt.ok(child) {\n                        push(children, child);\n                        if (i == 0) { group = some(process.group(child)); }\n                    }\n                    SpawnAttempt.not_found {\n                        rollback(children, group, prepared.opened, pipes, input, output, error);\n                        return LaunchResult.invalid("command could not be resolved");\n                    }\n                    SpawnAttempt.failed(number) {\n                        rollback(children, group, prepared.opened, pipes, input, output, error);\n                        return LaunchResult.launch_failed(failure(command, number));\n                    }\n                }\n            }\n\n            close_fds(prepared.opened);\n            close_pipes(pipes);\n            close_stdio(input, output, error);\n            return LaunchResult.ok(LiveJob { children: children, group: group });\n        }\n    }\n    trap;\n'''
if s.count(old) != 1:
    raise SystemExit(f'prepared-pipeline control flow: expected one match, got {s.count(old)}')
s = s.replace(old, new, 1)

p.write_text(s)
